#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApps.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum msevtmgt_nooryes
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		No = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Yes = 100000002,
	}
}
#pragma warning restore CS1591
