#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApps.Model
{
	
	
	/// <summary>
	/// Consent level for contact
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public enum msgdpr_gdpr_consent_option_set
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		@__1Consent = 587030001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		@__2Transactional = 587030002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		@__3Subscriptions = 587030003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		@__4Marketing = 587030004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		@__5Profiling = 587030005,
	}
}
#pragma warning restore CS1591
